### ISSUE TITLE
Iteration 1 - Nice UI but formatting issue on radio buttons

### ISSUE THREAD

**Issue by jbrucker** [sirateek/ku-polls#12]
Great looking UI and graphs, but in the list of choices the radio buttons
are not on same line as choice text.

[Siratee.pdf](https://github.com/sirateek/ku-polls/files/7183016/Siratee.pdf)
.

**Comment by sirateek** [comment]
On the detail page, I wrote [CSS for customizing the radio button][CustomizeCSS].

I never see this issue during the development. So I wonder this could be unsupported CSS rendering?

First, Just to make sure that you are using the latest commit in the branch `iteration1` ?.
If so, Could you please provide me the information about the browser and its version that you use?

Also, if you have any ideas about this bug. Please let me know :)

This is what I see right now.
![1631881616058](https://user-images.githubusercontent.com/25188615/133872160-d8d804d5-e694-498c-aa9a-e8b3a427b334.jpg)
(I built from this commit 61ca9dd)

[CustomizeCSS]: https://github.com/sirateek/ku-polls/blob/61ca9ddc43d6a04e189b8ac72bfa8ed021da1959/polls/static/polls/css/detail.css

**Comment by sirateek** [comment]
I found that **Django won't serve the static content when it's on the production mode** (`DEBUG=False`) 
So the logo and the CSS file I wrote are missing (But the bootstrap is there because I used the CDN version).
That is why the page formatting is messed.

Thank you 😄🙏.

**Comment by sirateek** [comment]
After further research. [Django documents][DjangoDoc] recommend that the static files should be served separately when in production mode.
So there is nothing that I can do with the code in the repository since it depends on how you want to deploy this app on your server.

If you're running this on your own computer, I suggest you turn the production mode off (`DEBUG=True`).

But if you want to serve this app on your server, You can do the following steps to collect the static files and serve them on your server

1. Open the file `/config/settings.py` and provide the `STATIC_ROOT` config to be the path to the output directory where you want all of the static files will be copied to.

> ```python
> ...
> # Static files (CSS, JavaScript, Images)
> # https://docs.djangoproject.com/en/3.2/howto/static-files/
> 
> STATIC_URL = '/static/'
> STATIC_ROOT = 'static/'
> ...
> ```

2. On the top directory of the project. Run this command to collect all static files across the project.

> ```bash
> $ python3 manage.py collectstatic
> ```

3. In the output directory, You'll have folders and files like this

> ```
> static/
>   |-> admin/
>   |       |-> ...
>   |-> polls/
>           |-> css/
>           |       |-> ...
>           |-> images/
>                   |-> ...
> ```

4. You can copy those static files to serve on your server web server or cloud CDN provider as you want.
5. Don't forget to update the `STATIC_URL` config in `/config/settings.py` to point to those static files you serve in the last step.

I'm closing this now. Thank you for pointing this out to me 🙏


[DjangoDoc]: https://docs.djangoproject.com/en/3.2/howto/static-files/deployment/
